from .registration import AddRegistrationOnInstantiation
from .constructor import GenerateConstructor
from .annotation_from_methods import ExtendAnnotationFromMethods
from .public_methods import WrapPublicMethods
